server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-api-rest
    driver-class-name: org.postgresql.Driver
    password: admin
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect